HOMOPHONE_LETTER_ERROR = {
    "a": ["ă"],
    "á": ["ắ"],
    "à": ["ằ"],
    "ả": ["ã", "ẵ", "ẳ"],
    "ã": ["ả", "ẳ", "ẵ"],
    "ạ": ["ặ"],
    "ă": ["a"],
    "ắ": ["á"],
    "ằ": ["à"],
    "ẳ": ["ẵ", "ã", "ả"],
    "ẵ": ["ẳ", "ả", "ã"],
    "ặ": ["ạ"],
    "â": ["ơ"],
    "ấ": ["ớ"],
    "ầ": ["ờ"],
    "ẩ": ["ẫ", "ở", "ỡ"],
    "ẫ": ["ẩ", "ỡ", "ở"],
    "ậ": ["ợ"],
    "b": ["p"],
    "c": ["k", "q"],
    "ch": ["tr"],
    "d": ["gi", "r"],
    "ẻ": ["ẽ"],
    "ẽ": ["ẻ"],
    "ể": ["ễ"],
    "ễ": ["ể"],
    "g": ["gh"],
    "gh": ["g"],
    "gi": ["d", "r"],
    "i": ["y"],
    "í": ["ý"],
    "ì": ["ỳ"],
    "ỉ": ["ĩ", "ỹ", "ỷ"],
    "ĩ": ["ỉ", "ỷ", "ỹ"],
    "ị": ["ỵ"],
    "k": ["c", "q"],
    "l": ["n"],
    "n": ["l"],
    "ng": ["ngh"],
    "ngh": ["ng"],
    "ỏ": ["õ"],
    "õ": ["ỏ"],
    "ổ": ["ỗ"],
    "ỗ": ["ổ"],
    "ơ": ["â"],
    "ớ": ["ấ"],
    "ờ": ["ầ"],
    "ở": ["ỡ", "ẫ", "ẩ"],
    "ỡ": ["ở", "ẩ", "ẫ"],
    "ợ": ["ậ"],
    "p": ["b"],
    "q": ["c", "k"],
    "r": ["d", "gi"],
    "s": ["x"],
    "tr": ["ch"],
    "ủ": ["ũ"],
    "ũ": ["ủ"],
    "ử": ["ữ"],
    "ữ": ["ử"],
    "x": ["s"],
    "y": ["i"],
    "ý": ["í"],
    "ỳ": ["ì"],
    "ỷ": ["ỹ", "ĩ", "ỉ"],
    "ỹ": ["ỷ", "ỉ", "ĩ"],
    "ỵ": ["ị"],
    # TODO accent of double/triple vowel
    "iê": ["yê", "ia", "ya"],
    "yê": ["iê", "ia", "ya"],
    "ia": ["iê", "yê", "ya"],
    "ya": ["iê", "yê", "ia"],
    "uô": ["ua"],
    "ua": ["uô"],
    "ươ": ["ưa"],
    "ưa": ["ưo"],
    "ay": ["ây"],
    "ây": ["ay"],
    "eo": ["oe", "oeo"],
    "oe": ["eo", "oeo"],
    "iêu": ["yêu"],
    "yêu": ["iêu"],
    "oai": ["oay"],
    "oay": ["oai"],
    "oeo": ["eo", "oe"],
    "A": ["Ă"],
    "Á": ["Ắ"],
    "À": ["Ằ"],
    "Ả": ["Ã", "Ẵ", "Ẳ"],
    "Ã": ["Ả", "Ẳ", "Ẵ"],
    "Ạ": ["Ặ"],
    "Ă": ["A"],
    "Ắ": ["Á"],
    "Ằ": ["À"],
    "Ẳ": ["Ẵ", "Ã", "Ả"],
    "Ẵ": ["Ẳ", "Ả", "Ã"],
    "Ặ": ["Ạ"],
    "Â": ["Ơ"],
    "Ấ": ["Ớ"],
    "Ầ": ["Ờ"],
    "Ẩ": ["Ẫ", "Ỡ", "Ở"],
    "Ẫ": ["Ẩ", "Ở", "Ỡ"],
    "Ậ": ["Ợ"],
    "B": ["P"],
    "C": ["K", "Q"],
    "CH": ["TR"],
    "Ch": ["Tr"],
    "D": ["GI", "Gi", "R"],
    "Ẻ": ["Ẽ"],
    "Ẽ": ["Ẻ"],
    "Ể": ["Ễ"],
    "Ễ": ["Ể"],
    "G": ["GH", "Gh"],
    "GH": ["G"],
    "Gh": ["G"],
    "GI": ["D", "R"],
    "Gi": ["D", "R"],
    "I": ["Y"],
    "Í": ["Ý"],
    "Ì": ["Ỳ"],
    "Ỉ": ["Ĩ", "Ỹ", "Ỷ"],
    "Ĩ": ["Ỉ", "Ỷ", "Ỹ"],
    "Ị": ["Ỵ"],
    "K": ["C", "Q"],
    "L": ["N"],
    "N": ["L"],
    "NG": ["NGH"],
    "Ng": ["Ngh"],
    "NGH": ["NG"],
    "Ngh": ["Ng"],
    "Ỏ": ["Õ"],
    "Õ": ["Ỏ"],
    "Ổ": ["Ỗ"],
    "Ỗ": ["Ổ"],
    "Ơ": ["Â"],
    "Ớ": ["Ấ"],
    "Ờ": ["Ầ"],
    "Ở": ["Ỡ", "Ẫ", "Ẩ"],
    "Ỡ": ["Ở", "Ẩ", "Ẫ"],
    "Ợ": ["Ậ"],
    "P": ["B"],
    "Q": ["C", "K"],
    "R": ["D", "GI", "Gi"],
    "S": ["S"],
    "TR": ["CH"],
    "Tr": ["Tr"],
    "Ủ": ["Ũ"],
    "Ũ": ["Ủ"],
    "Ử": ["Ữ"],
    "Ữ": ["Ử"],
    "X": ["S"],
    "Y": ["I"],
    "Ý": ["Í"],
    "Ỳ": ["Ì"],
    "Ỷ": ["Ỹ", "Ĩ", "Ỉ"],
    "Ỹ": ["Ỷ", "Ỉ", "Ĩ"],
    "Ỵ": ["Ị"],
    # TODO accent of double/triple vowel
    "IÊ": ["YÊ", "IA", "YA"],
    "YÊ": ["IÊ", "IA", "YA"],
    "IA": ["IÊ", "YÊ", "YA"],
    "YA": ["IÊ", "YÊ", "IA"],
    "UÔ": ["UA"],
    "UA": ["UÔ"],
    "ƯƠ": ["ƯA"],
    "ƯA": ["ƯƠ"],
    "AY": ["ÂY"],
    "ÂY": ["AY"],
    "EO": ["OE", "OEO"],
    "OE": ["EO", "OEO"],
    "IÊU": ["YÊU"],
    "YÊU": ["IÊU"],
    "OAI": ["OAY"],
    "OAY": ["OAI"],
    "OEO": ["EO", "OE"],
}

HOMOPHONE_SINGLE_WORD_ERROR = {
    "bàn": "bàng",
    "bàng": "bàn",
    "dày": "giày",
    "dầy": "giầy",
    "dây": "giây",
    "chải": "trải",
    "chai": "trai",
    "chầy": "trầy",
    "chéo": "tréo",
    "chỉn": "chỉnh",
    "chơi": "trơi",
    "chuyện": "truyện",
    "giằng": "dằng",
    "giãy": "dãy",
    "giẫy": "dẫy",
    "giấu": "dấu",
    "giở": "dở",
    "giày": "dày",
    "giầy": "giầy",
    "này": "rày",
    "quốc": "cuốc",
    "rày": "này",
    "suất": "xuất",
    "sử": "xử",
    "trải": "chải",
    "trai": "chai",
    "trầy": "chầy",
    "tréo": "chéo",
    "truyện": "chuyện",
    "xuất": "suất",
    "xử": "sử",
}


HOMOPHONE_DOUBLE_WORD_ERROR = {
    "bạt mạng": "bạc mạng",
    "bàng quang": "bàng quan",
    "bàng quan": "bàng quang",
    "căn dặn": "căn vặn",
    "chặn đường": "chặng đường",
    "chặng đường": "chặn đường",
    "chắp bút": "chấp bút",
    "chấp bút": "chắp bút",
    "chín muồi": "chín mùi",
    "chín chắn": "chính chắn",
    "chỉn chu": "chỉnh chu",
    "chua xót": "chua sót",
    "chẩn đoán": "chuẩn đoán",
    "cọ xát": "cọ sát",
    "dè sẻn": "dè xẻn",
    "đầy ắp": "đầy ấp",
    "đề huề": "đều huề",
    "điểm xuyết": "điểm xuyến",
    "độc giả": "đọc giả",
    "đường sá": "đường xá",
    "giành dật": "dành giật",
    "giấu giếm": "dấu diếm",
    "giả thuyết": "giả thiết",
    "giả thiết": "giả thuyết",
    "hàm súc": "hàm xúc",
    "hằng ngày": "hàng ngày",
    "kể truyện": "kể chuyện",
    "khắt khe": "khắc khe",
    "khảng khái": "khẳng khái",
    "lãng mạn": "lãng mạng",
    "mải mê": "mãi mê",
    "muồi mẫn": "mùi mẫn",
    "nhậm chức": "nhận chức",
    "nói suôn": "nói suông",
    "nói suông": "nói suôn",
    "nói chuyện": "nói truyện",
    "phong thanh": "phong phanh",
    "phong phanh": "phong thanh",
    "phố xá": "phố sá",
    "xán lạn": "sáng lạng",
    "sáp nhập": "sát nhập",
    "se sua": "xe xua",
    "sớn sác": "xớn xác",
    "suôn sẻ": "suông sẻ",
    "tham quan": "thăm quan",
    "tri thức": "trí thức",
    "trí thức": "tri thức",
    "tựu trung": "tựu chung",
    "vãng cảnh": "vãn cảnh",
    "xạo xự": "xạo sự",
    "xoay xở": "xoay sở",
    "súc tích": "xúc tích",
}
