openapi: 3.0.0
info:
  title: Spelling Correction API
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /spell_check:
    post:
      summary: Check the spelling of the text
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to be spell checked
                  example: Thi iz a smple text
      responses:
        200:
          description: The spell corrected text
          content:
            application/json:
              schema:
                type: string
                example: This is a 
